name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"  # Runs when a version tag (e.g., v1.0.0) is pushed

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Configure Poetry for PyPI
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Build the package
        run: poetry build

      - name: Publish to PyPI
        run: poetry publish
